import type { Metadata } from "next";
import Navbar from "@/app/component/navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function StoreLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
    <Navbar />
    {children}
  </section>
  );
}
