import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

import SessionProvider from "./component/SessionProvider";
import { getServerSession } from "next-auth";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Matter",
  description: "Generated by create next app",
  icons: {
    icon: ["/pngtree.png"],
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="font-noto">
          <SessionProvider session={session}>
            {children}
            </SessionProvider>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
